# Generated by Django 6.1 on 2026-09-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='city',
            field=models.CharField(default='wilmington', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='country',
            field=models.CharField(default='USA', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='state',
            field=models.CharField(default='NC', max_length=60),
            preserve_default=False,
        ),
    ]
