# Generated by Django 6.1 on 2026-09-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0002_trip_city_trip_country_trip_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='zip',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
