export const mockGroups = [
  {
    id: 1,
    name: "Oahu Crew",
    created_on: "2026-05-12",
    member_count: 5,
    is_member: true,
    is_leader: true,
  },
  {
    id: 2,
    name: "Bachelor Party Crew",
    created_on: "2026-06-01",
    member_count: 8,
    is_member: true,
    is_leader: false,
  },
  {
    id: 3,
    name: "Ski Squad",
    created_on: "2026-04-22",
    member_count: 6,
    is_member: false,
    is_leader: false,
  },
  {
    id: 4,
    name: "Family Reunion",
    created_on: "2026-03-02",
    member_count: 12,
    is_member: false,
    is_leader: false,
  },
  {
    id: 5,
    name: "College Friends",
    created_on: "2026-02-14",
    member_count: 7,
    is_member: false,
    is_leader: false,
  },
  {
    id: 6,
    name: "Work Retreat",
    created_on: "2026-01-30",
    member_count: 9,
    is_member: false,
    is_leader: false,
  },
];

export const mockTrips = [
  {
    id: 1,
    group_id: 2,
    group_name: "Bachelor Party Crew",
    name: "Vegas Bachelor Party",
    city: "Las Vegas",
    state: "NV",
    country: "USA",
    vote_count: 4,
    has_voted: true,
  },
  {
    id: 2,
    group_id: 1,
    group_name: "Oahu Crew",
    name: "Oahu Reunion",
    city: "Honolulu",
    state: "HI",
    country: "USA",
    vote_count: 2,
    has_voted: false,
  },
  {
    id: 3,
    group_id: 1,
    group_name: "Oahu Crew",
    name: "Denver Ski Weekend",
    city: "Denver",
    state: "CO",
    country: "USA",
    vote_count: 1,
    has_voted: false,
  },
];

export const mockActivities = [
  {
    id: 1,
    trip_id: 1,
    name: "Pool Party at MGM",
    description: "Cabana + day passes for the group",
    street: "3799 S Las Vegas Blvd",
    city: "Las Vegas",
    state: "NV",
    zip: "89109",
    country: "USA",
    place_id: "ChIJ_mock_mgm_pool",
    cost_estimate_cents: 15000,
    vote_count: 5,
    has_voted: true,
  },
  {
    id: 2,
    trip_id: 1,
    name: "Steakhouse Dinner",
    description: "Group dinner, night one",
    street: "3325 S Las Vegas Blvd",
    city: "Las Vegas",
    state: "NV",
    zip: "89109",
    country: "USA",
    place_id: "ChIJ_mock_steakhouse",
    cost_estimate_cents: 12000,
    vote_count: 3,
    has_voted: false,
  },
  {
    id: 3,
    trip_id: 1,
    name: "Helicopter Tour",
    description: "Grand Canyon sunset flight",
    street: "5596 Haven St",
    city: "Las Vegas",
    state: "NV",
    zip: "89119",
    country: "USA",
    place_id: "",
    cost_estimate_cents: 45000,
    vote_count: 2,
    has_voted: false,
  },
];

export const mockMembers = [
  {
    id: 1,
    group_id: 1,
    user_id: 1,
    username: "simon",
    email: "simon@example.com",
    read_access: true,
    write_access: true,
    is_leader: true,
  },
  {
    id: 2,
    group_id: 1,
    user_id: 2,
    username: "kaylee",
    email: "kaylee@example.com",
    read_access: true,
    write_access: true,
    is_leader: false,
  },
  {
    id: 3,
    group_id: 1,
    user_id: 3,
    username: "cody",
    email: "cody@example.com",
    read_access: true,
    write_access: false,
    is_leader: false,
  },
  {
    id: 4,
    group_id: 1,
    user_id: 4,
    username: "mohamed",
    email: "mohamed@example.com",
    read_access: true,
    write_access: false,
    is_leader: false,
  },
  {
    id: 5,
    group_id: 1,
    user_id: 5,
    username: "abdel",
    email: "abdel@example.com",
    read_access: false,
    write_access: false,
    is_leader: false,
  },
  {
    id: 6,
    group_id: 2,
    user_id: 1,
    username: "simon",
    email: "simon@example.com",
    read_access: true,
    write_access: false,
    is_leader: false,
  },
  {
    id: 7,
    group_id: 2,
    user_id: 6,
    username: "angel",
    email: "angel@example.com",
    read_access: true,
    write_access: true,
    is_leader: true,
  },
];
